### ISSUE TITLE
Is it possible to give more granular control over the framerate cap of each hud element?

### ISSUE THREAD

**Issue by aaaa2aaaa** [tr7zw/Exordium#13]
It totally makes sense for bossbars, overlays, the crosshair, and scoreboard to run at at little as 5fps; however, things like chat, titles, and the debug menu you probably want to run at minimum 30fps. The inventory menu feels really choppy at <1/2 your refresh rate, and world rendering speed matters less while you're in your inventory so it makes sense to have the framerates be high there. Because of this, it would be useful to have control over the framerate of individual parts of the GUI if possible. Would it be possible to implement something like this or no?

**Comment by tr7zw** [comment]
The question is the diminishing returns. Maintaining multiple buffers might be slower than just rendering it. The debug menu is something you really don't want at a high refresh rate because of how slow it is(its the worst part), and why high framerate chat? Titles I can kinda get due to the fading effect otherwise being choppy(maybe exclude them/temporarily raise the framerate when a title is up?)

**Comment by aaaa2aaaa** [comment]
If having multiple buffers causes slowdowns then yeah don't do that, temporarily raising the framerate while the inventory is open or titles show up would 
might be an acceptable solution to the problem I described though.
Unrelated but thanks for making fastergui btw, literally doubled my framerate with shaders off. Amazing mod.

**Comment by tr7zw** [comment]
The latest versions do have this.
