### ISSUE TITLE
CurseForge version is outdated

### ISSUE THREAD

**Issue by Madis0** [tr7zw/Exordium#32]
Exordium updated to 1.0.2 yesterday, but only Modrinth got the update.

**Comment by tr7zw** [comment]
See the patch notes, that was mainly testing auto publishing mod updates(that's why it was only on modrinth for the first test, because I didn't assume it to work). The update just changed a default setting and the version number in the mod yaml. Nothing that asap needs to be on Curseforge, probably going to be 1.0.3.
