### ISSUE TITLE
Custom font on signs is cropped

### ISSUE THREAD

**Issue by Felix14-v2** [tr7zw/Exordium#49]
During the development of the map for Realms, I noticed that the image of the text with custom font is cropped in a strange way:
![Screenshot_20221226-110143](https://user-images.githubusercontent.com/75726196/209544240-58dc3ce9-cd84-4f0b-98b3-8db47f68e5ff.jpg)
![Screenshot_20221226-125307](https://user-images.githubusercontent.com/75726196/209544278-90cfb0e6-5fb7-45a9-8373-ae95a31dc025.jpg)

<details>
<summary>Expected behavior (Vanilla/Sign Buffering disabled)</summary>

![image (1)](https://user-images.githubusercontent.com/75726196/209544424-815efd44-29a4-4cf4-8b21-9fd0c3075ad5.png)
![image (2)](https://user-images.githubusercontent.com/75726196/209544427-0daef735-5fa7-41bb-b9b9-f5afa7f3b6f9.png)
</details>

<details>
<summary>Without mod and resourcepack</summary>

![image (3)](https://user-images.githubusercontent.com/75726196/209544564-adc8f8d5-7d70-4f27-bd44-64cd4d78c03d.png)
</details>

Is it possible to fix that behavior? As I understand from #48 , sign optimization works with great limitations in relation to custom fonts.

**Comment by tr7zw** [comment]
Like you linked with #48, this entire feature assumes vanilla signs and fonts. Adding support for HD fonts or really unusual use cases like this one is not really planned.

**Comment by Felix14-v2** [comment]
Maybe, for compatibility, it is possible to add settings for changing the maximum resolution and offset of the text outside the sign? Custom fonts are quite often used in maps and minigames.

**Comment by tr7zw** [comment]
For people that play maps like that, they should just turn off the feature or remove the mod. Increasing the resolution doesn't sound like a good idea, since it would eat a ton more gpu memory. Rather, I'd like to decrease the texture size to actually fit the sign where vanilla does render to. Right now it's about 50% too big.

**Comment by Felix14-v2** [comment]
Well, if you do not plan to change anything in this area, feel free to close the issue. Thank you for your time anyway!

**Comment by tr7zw** [comment]
As a background: I can't know how "high res" the font is, or how much custom hacky fonts render outside of the intended sign area. So it's not really possible(without a ton of dirty tricks/assumptions) to do this right. That's why I just limit the scope to vanilla use-cases, without odd resource packs/mods.
